name: umkm_batik
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  google_fonts: ^4.0.4
  sqflite: ^2.2.8+4
  path_provider: ^2.0.5
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.0
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ado.jpg
    - assets/images/ado2.jpg
    - assets/images/griyabatik_bru.png
    - assets/images/griyabatik_hitam.png
    - assets/images/griyabatik_putih.png
    - assets/images/asset5.png

flutter_native_splash:
  color: "#2596be"
  image: assets/images/Asset5.png
  android: true
  ios: true

